FROM python:3.9-slim
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt --no-cache-dir
RUN apt-get update
RUN apt-get -y install fonts-dejavu
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "foodgram.wsgi", "--reload"]