version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: vedy22/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media
  
  frontend:
    image: vedy22/foodgram_frontend
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: vedy22/foodgram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/app/media
